name: app
description: CopyCrab Delivery.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  
  intl: ">=0.15.0 <1.0.0"
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter   

flutter:

  uses-material-design: true

  assets:
    - assets/person-male.png
    - assets/customer.jpg
    - assets/driver.jpg
    - assets/food.jpg
    - assets/animals.png
    - assets/AfterYou.jpg
    - assets/CoCo.png
    - assets/Fuji.png
    - assets/Kamu.png
    - assets/Swensens.jpg
    - assets/TomYum.jpg
    - assets/Starbucks.jpg
    - assets/Bingsu.jpg
    - assets/a.jpg
    - assets/KFC.jpeg
    - assets/Pepe.png
    - assets/acai1.jpg
    - assets/acai2.jpg


    - assets/foods/bonchon.jpg
    - assets/foods/bua.jpg
    - assets/foods/chanom.jpg
    - assets/foods/noodle.jpg
    - assets/foods/pla.jpg
    - assets/foods/tum.jpg

  fonts:
    - family: Opun
      fonts:
        - asset: fonts/Opun-Regular.ttf